# Generated by Django 2.2.26 on 2022-05-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_datauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
